// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart'show FirebaseOptions, Firebase;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter/material.dart';
import 'package:softskills/main.dart';
// Ensure this import is present and correct

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(MyApp()); // Replace with your main app widget
}

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnGqqzG-Bjbwi2lauT3Smmb0_f13_esgs',
    appId: '1:528764579265:web:ea78fc003e57b4ce9e1340',
    messagingSenderId: '528764579265',
    projectId: 'softskills-1e29c',
    authDomain: 'softskills-1e29c.firebaseapp.com',
    storageBucket: 'softskills-1e29c.appspot.com',
    measurementId: 'G-95BEXHJ4KW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrMXa6uF8-OfmUGqWNi-yk0_vwBmF93i0',
    appId: '1:528764579265:android:78245bc2832444af9e1340',
    messagingSenderId: '528764579265',
    projectId: 'softskills-1e29c',
    storageBucket: 'softskills-1e29c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqdQ2aqBcHULVaTW4-Q56hMsnn2NGwoBs',
    appId: '1:528764579265:ios:ac3a88c666ca7fcb9e1340',
    messagingSenderId: '528764579265',
    projectId: 'softskills-1e29c',
    storageBucket: 'softskills-1e29c.appspot.com',
    iosBundleId: 'com.example.softskills',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqdQ2aqBcHULVaTW4-Q56hMsnn2NGwoBs',
    appId: '1:528764579265:ios:ac3a88c666ca7fcb9e1340',
    messagingSenderId: '528764579265',
    projectId: 'softskills-1e29c',
    storageBucket: 'softskills-1e29c.appspot.com',
    iosBundleId: 'com.example.softskills',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnGqqzG-Bjbwi2lauT3Smmb0_f13_esgs',
    appId: '1:528764579265:web:d84ee4cd4e3e9b589e1340',
    messagingSenderId: '528764579265',
    projectId: 'softskills-1e29c',
    authDomain: 'softskills-1e29c.firebaseapp.com',
    storageBucket: 'softskills-1e29c.appspot.com',
    measurementId: 'G-KK4PED90RT',
  );
}
