name: softskills
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  flutter_spinkit: ^5.1.0
  lottie: ^2.3.2 
  cupertino_icons: ^1.0.6
  file_picker: ^8.1.3
  image_picker: ^1.1.2
  intl: ^0.19.0 
  introduction_screen: ^3.1.9
  table_calendar: ^3.1.2
  google_fonts: ^6.0.1
  flutter_sound: ^8.4.0
  permission_handler: ^11.3.1
  record: ^4.4.4
  google_sign_in: ^6.2.2
  path_provider: ^2.1.5
  open_file: ^3.3.2
  http: ^1.3.0
  share_plus: ^7.0.2
  dio: ^5.8.0+1
  flutter_file_downloader: ^1.1.0
  url_launcher: ^6.3.1
  audioplayers: ^5.2.1 
  persistent_bottom_nav_bar: any
  hmssdk_flutter: ^1.10.3
  hms_room_kit: ^1.1.5
  #hms_video_plugin: ^0.0.2
  firebase_core: ^3.12.0 
  firebase_storage: ^12.4.2


dependency_overrides:
  flutter_sound: 9.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/apple.png
    - assets/google.png
    - assets/bg.png
    - assets/image1.png
    - assets/image2.png 
    - assets/image3.png
    - assets/bg-01.png

  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf
        - asset: assets/fonts/DancingScript-Bold.ttf
          weight: 700

    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Light.otf
          weight: 300

