platform :ios, '12.0' # Or higher, depending on your project
use_frameworks!
target.build_configurations.each do |config|
  config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
    '$(inherited)',
    ## dart: PermissionGroup.camera
    'PERMISSION_CAMERA=1',

    ## dart: PermissionGroup.microphone
    'PERMISSION_MICROPHONE=1',

    ## dart: PermissionGroup.bluetooth
    'PERMISSION_BLUETOOTH=1',
  ]
end
